# Ansible template to configure the Jenkins Master
---
- hosts: default
  become: yes
  gather_facts: true
  vars_files:
    - jenkins_vars.yml
  tasks:
    - name: Download dependencies
      yum:
        name: "{{ dependencies }}"
        state: present
    - name: Download Java
      yum:
        name: "java-1.{{ java_version }}-openjdk"
        state: present
    - name: Get the Jenkins swarm client downloaded
      get_url:
        url: "https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/swarm-client/{{ swarm_version }}/swarm-client-{{ swarm_version }}.jar"
        dest: "/home/ec2-user/swarm-client.jar"
