# Intall Jenkins
---
- name: Install Jenkins dependencies
  yum:
    name: "{{ dependencies }}"
    state: latest

- name: Download Jenkins repository
  get_url:
    url: "{{ jenkins_repo.repo_url }}"
    dest: "/etc/yum.repos.d/jenkins.repo"

- name: Import Jenkins repo GPG key
  rpm_key:
    key: "{{ jenkins_repo.repo_key }}"
    state: present

- name: Install Jenkins
  yum:
    name: jenkins
    state: latest

- name: Start Jenkins service
  service:
    name: jenkins
    state: started
    enabled: yes
