# Install and configure Java and the dependencies for Jenkins
---
# Install Java
- name: Install Java
  yum:
    name: "{{ java.package }}"
    state: latest

# Install dependencies
- name: Install Jenkins dependencies
  yum:
    name: "{{ dependencies }}"
    state: latest
