# tasks file for jenkins
---
# Install and configure java
- include_tasks: install_dependencies.yml

# Install Jenkins
- include_tasks: install_jenkins.yml

# Configure Jenkins
- include_tasks: configure_jenkins.yml

# Wait for Jenkins to be up
- name: Wait for Jenkins to start
  uri:
    url: "http://{{ jenkins_hostname }}:{{ jenkins_port }}{{ jenkins_url_path }}"
    method: GET
    return_content: yes
    timeout: 5
    body_format: raw
    follow_redirects: yes
    status_code: 200,403
  changed_when: false
  check_mode: false
  register: jenkins_access_result
  until: ( jenkins_access_result.status == 403 or jenkins_access_result == 200 )
  retries: "{{ jenkins_access.retries }}"
  delay: "{{ jenkins_access.delay }}"

  ## Download the Jenkins CLI
- name: Get the Jenkins CLI
  get_url:
    url: "http://{{ jenkins_hostname }}:{{ jenkins_port }}{{ jenkins_url_path }}/jnlpJars/jenkins-cli.jar"
    dest: "{{ jenkins_cli_path }}"
  
# Get the initial admin password and register it in a fact
- name: Get initial admin password file
  slurp:
    src: "{{ jenkins_home_folder }}/secrets/initialAdminPassword"
  register: initialAdminPassword
  no_log: yes

- name: Register inital admin password
  set_fact:
    initial_admin_password: "{{ initialAdminPassword.content | b64decode | trim }}"
  no_log: yes

# Register users
- include_tasks: register_users.yml

# Install plugins
- include_tasks: install_plugins.yml
