# Ansible template to configure the Jenkins Master
---
- hosts: master_host
  become: true
  gather_facts: true
  vars:
    java_version: 8.0
    jenkins_use_stable_version: true
    jenkins_home_folder: /var/lib/jenkins
    jenkins_host_user: jenkins
    jenkins_host_group: "{{ jenkins_host_user }}"
    jenkins_hostname: localhost
    jenkins_port: 8080
    jenkins_url_path: ""
  roles:
    - role: roles/jenkins_master
  tasks:
    - name: Get the Jenkins initial admin password file
      fetch:
        src: "{{ jenkins_home_folder }}/secrets/initialAdminPassword"
        dest: "{{ module_path }}/"
        flat: true
